### ISSUE TITLE
App crashes after build apk 

### ISSUE THREAD

**Issue by PJohNSK** [Ingenio/flutter_pubnub#12]
**Fatal Exception: java.lang.NullPointerException
throw with null exception**

Fatal Exception: java.lang.NullPointerException: throw with null exception
       at com.pubnub.api.models.server.SubscribeMetadata.getTimetoken(SubscribeMetadata.java:3)
       at com.pubnub.api.managers.SubscriptionManager$5.a(SubscriptionManager.java:201)
       at com.pubnub.api.managers.SubscriptionManager$5.a(SubscriptionManager.java:2)
       at com.pubnub.api.endpoints.Endpoint$1.a(Endpoint.java:45)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:37)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by olivierbrand** [comment]
We have fixed it on our side and is in QA. The issue surfaced with newer versions of flutter and the lack of code obfuscation rules on our side. Planning to update the plugin in next 2 days

**Comment by olivierbrand** [comment]
We added the proguard rules in the plugin, now the issue is fixed.
